CREATE TABLE CAR(
	ID INT AUTO_INCREMENT,
	MAKE VARCHAR(255),
	MODEL VARCHAR(255),
	REGISTRATION VARCHAR(255),
	YEAR INT,
	INSPECTION_DATE DATE,
	ENGINE_SIZE INT,
	ENGINE_POWER INT
);

INSERT INTO CAR(MAKE, MODEL, REGISTRATION, YEAR, INSPECTION_DATE, ENGINE_SIZE, ENGINE_POWER) SELECT * FROM CSVREAD('C:\fleetmanager\fleetmanager\src\main\resources\car.csv');